---
title: "Meta_Analysis_Venn_Diagram"
output: html_document
date: "2024-09-03"
---
#### Venn Diagram for Biomarkers

```{r}
library(ggVennDiagram)
```

```{r}
Ab_deposition = c(1, 2, 3, 4, 5, 6, 7, 10, 13, 16, 18, 19, 23, 25, 26, 27)
IL_1B = c(6, 7, 9, 14, 16)
Microglia = c(6, 9, 13, 16, 18)
GFAP = c(5, 9, 13, 19, 28)
```

```{r}
biomarkers <- list(Ab_deposition, IL_1B, Microglia, GFAP)
ggVennDiagram(biomarkers, category.names = c("Abeta", "IL-1B", "Microglia", "GFAP")) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF")
```

#### Behavioral Venn Diagram
```{r}
Discrimination_index = c(2, 5, 6, 8, 9, 14)
Time_spent_in_target_quadrant = c(1, 3, 4, 6, 8, 9, 10, 12, 13, 14, 15, 17, 18, 20, 23, 27, 28)
Number_platform_crossed = c(1, 3, 4, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 25)
Escape_Latency = c(3, 4, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28)
```

```{r}
behaviorals <- list(Discrimination_index, Time_spent_in_target_quadrant, Number_platform_crossed, Escape_Latency)
ggVennDiagram(behaviorals, category.names = c("Discrimination idx", "Time spent in target quadrant", "Number platform crossed", "Escape Latency")) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF")
```

