---
title: "Meta_Analysis_escape_latency"
output: html_document
date: "2024-08-06"
---
```{r}
library(meta)
library(metafor)
library(metasens)
library(dplyr)
library(readxl)
library(ggplot2)
library(netmeta)
library(igraph)
```

#### Escape latency
##### Import dataset
```{r}
data_dir <- "/Users/mohanyang/Desktop/Meta-Analysis/Notes and data for listed articles"
subdirs <- list.dirs(data_dir, recursive = FALSE)

control_data_escape_latency <- data.frame()
treatment_data_escape_latency <- data.frame()

for (subdir in subdirs) {
  # Define the path to the Ab protein deposition file
  escape_latency_file_path <- file.path(subdir, "Long_format_escape_latency(sec).xlsx")
  
  # Check if the file exists
  if (file.exists(escape_latency_file_path)) {
    # Read the data from the file
    data_escape_latency_single <- read_excel(escape_latency_file_path)
  
  # State control groups and treatment groups
  control_groups <- c("5xFAD", "5xFAD+shWnt5a", "APP/PS1", "5xFAD/3xTg", "3xTg", "cDKO")
  treatment_groups <- c("5xFAD+EA", "5xFAD+shWnt5a+EA", "APP/PS1+EA", "5xFAD/3xTg+EA", "APP/PS1+MA", "3xTg+EA", "cDKO+EA")
    
  # Filter data for control and treatment groups
  control_escape_latency_single <- data_escape_latency_single %>% filter(treatment_group %in% control_groups)
  treatment_escape_latency_single <- data_escape_latency_single %>% filter(treatment_group %in% treatment_groups)
    
  # Append the data to the respective data frames
  control_data_escape_latency <- rbind(control_data_escape_latency, control_escape_latency_single)
  treatment_data_escape_latency <- rbind(treatment_data_escape_latency, treatment_escape_latency_single)
  }
}
```

```{r}
control_data_escape_latency
```

```{r}
treatment_data_escape_latency
```

#####  Get the difference data between the base group and control group
```{r}
# Modify the treatment_group in the treatment data to remove "+EA" for inner join purpose
treatment_data_escape_latency <- treatment_data_escape_latency %>%
  mutate(treatment_group = gsub("\\+EA", "", treatment_group))

# Use inner_join to merge the data frames by paper_id, treatment_group, and brain_area
merged_data_escape_latency <- inner_join(control_data_escape_latency, treatment_data_escape_latency, 
                          by = c("paper_id", "treatment_group", "age(month)", "day"), 
                          suffix = c("_control", "_treatment"))

smd_data_escape_latency  <- merged_data_escape_latency %>% 
  mutate(
    
    sd_pooled = sqrt(((sample_size_control - 1) * sd_control^2 +
                      (sample_size_treatment - 1) * sd_treatment^2) /
                     (sample_size_control + sample_size_treatment - 2)),
    
    smd = (mean_treatment - mean_control) / sd_pooled,
    
    se_smd = sqrt((sample_size_control + sample_size_treatment) /
                  (sample_size_control * sample_size_treatment) +
                  (smd^2) / (2 * (sample_size_control + sample_size_treatment)))
  ) %>%
  select(paper_id, treatment_group, 'age(month)', acupoint_treatment, day, smd, se_smd)
```

```{r}
smd_data_escape_latency <- smd_data_escape_latency[
  order(as.numeric(as.character(smd_data_escape_latency$paper_id))), 
]

smd_data_escape_latency
```

```{r}
day1_data <- smd_data_escape_latency %>% filter(day == 1)
day2_data <- smd_data_escape_latency %>% filter(day == 2)
day3_data <- smd_data_escape_latency %>% filter(day == 3)
day4_data <- smd_data_escape_latency %>% filter(day == 4)
day5_data <- smd_data_escape_latency %>% filter(day == 5)

day4_data
```
```{r}
day1_data <- day1_data[
  order(as.numeric(as.character(day1_data$paper_id))), 
]

day2_data <- day2_data[
  order(as.numeric(as.character(day2_data$paper_id))), 
]

day3_data <- day3_data[
  order(as.numeric(as.character(day3_data$paper_id))), 
]

day4_data <- day4_data[
  order(as.numeric(as.character(day4_data$paper_id))), 
]

day5_data <- day5_data[
  order(as.numeric(as.character(day5_data$paper_id))), 
]
```

#####  Use Meta-Analysis package
###### Day 1 Data
```{r}
meta_analysis_escape_latency_day1 <- metagen(
  smd, 
  se_smd, 
  data = day1_data,
  studlab = paste(paper_id, treatment_group, as.character(`age(month)`), acupoint_treatment, day, sep = "  |  "),
  sm = "SMD",
  method.tau = "DL",   
  comb.fixed = FALSE,  
  comb.random = TRUE
)
summary(meta_analysis_escape_latency_day1)
```

```{r}
forest(meta_analysis_escape_latency_day1,
       studlab = TRUE,
       textpos = 4,
       leftcols = c("studlab", "effect", "ci"),
       leftlabs = c("Paper id | Control Group | Age(month) | Acupoint | Day", "SMD", "95% CI"),
       colgap.left = "8mm",
       rightcols = c("w.random"),
       rightlabs = c("Weight"))
```

```{r}
funnel(meta_analysis_escape_latency_day1,
       xlab = "Standardised Mean Difference",
       ylab = "Standard Error",
       col = "blue",
       bg = "lightblue",
       pch = 21, # Use filled circles
       cex = 1.5) # Increase point size
```
###### Day 2 Data
```{r}
meta_analysis_escape_latency_day2 <- metagen(
  smd, 
  se_smd,
  data = day2_data,
  studlab = paste(paper_id, treatment_group, as.character(`age(month)`), acupoint_treatment, day, sep = "  |  "),
  sm = "SMD",
  method.tau = "DL",   
  comb.fixed = FALSE,  
  comb.random = TRUE
)
summary(meta_analysis_escape_latency_day2)
```

```{r}
forest(meta_analysis_escape_latency_day2,
       studlab = TRUE,
       textpos = 4,
       leftcols = c("studlab", "effect", "ci"),
       leftlabs = c("Paper id | Control Group | Age(month) | Acupoint | Day", "SMD", "95% CI"),
       colgap.left = "8mm",
       rightcols = c("w.random"),
       rightlabs = c("Weight"))
```

```{r}
funnel(meta_analysis_escape_latency_day2,
       xlab = "Standardised Mean Difference",
       ylab = "Standard Error",
       col = "blue",
       bg = "lightblue",
       pch = 21, # Use filled circles
       cex = 1.5) # Increase point size
```


###### Day 3 Data
```{r}
meta_analysis_escape_latency_day3 <- metagen(
  smd, 
  se_smd, 
  data = day3_data,
  studlab = paste(paper_id, treatment_group, as.character(`age(month)`), acupoint_treatment, day, sep = "  |  "),
  sm = "SMD",
  method.tau = "DL",   
  comb.fixed = FALSE,  
  comb.random = TRUE
)
summary(meta_analysis_escape_latency_day3)
```

```{r}
forest(meta_analysis_escape_latency_day3,
       studlab = TRUE,
       textpos = 4,
       leftcols = c("studlab", "effect", "ci"),
       leftlabs = c("Paper id | Control Group | Age(month) | Acupoint | Day", "SMD", "95% CI"),
       colgap.left = "8mm",
       rightcols = c("w.random"),
       rightlabs = c("Weight"))
```

```{r}
funnel(meta_analysis_escape_latency_day3,
       xlab = "Standardised Mean Difference",
       ylab = "Standard Error",
       col = "blue",
       bg = "lightblue",
       pch = 21, # Use filled circles
       cex = 1.5) # Increase point size
```


###### Day 4 Data
```{r}
meta_analysis_escape_latency_day4 <- metagen(
  smd, 
  se_smd, 
  data = day4_data,
  studlab = paste(paper_id, treatment_group, as.character(`age(month)`), acupoint_treatment, day, sep = "  |  "),
  sm = "SMD",
  method.tau = "DL",   
  comb.fixed = FALSE,  
  comb.random = TRUE
)
summary(meta_analysis_escape_latency_day4)
```

```{r}
forest(meta_analysis_escape_latency_day4,
       studlab = TRUE,
       textpos = 4,
       leftcols = c("studlab", "effect", "ci"),
       leftlabs = c("Paper id | Control Group | Age(month) | Acupoint | Day", "SMD", "95% CI"),
       colgap.left = "8mm",
       rightcols = c("w.random"),
       rightlabs = c("Weight"))
```

```{r}
funnel(meta_analysis_escape_latency_day4,
       xlab = "Standardised Mean Difference",
       ylab = "Standard Error",
       col = "blue",
       bg = "lightblue",
       pch = 21, # Use filled circles
       cex = 1.5) # Increase point size
```

###### Day 5 Data
```{r}
meta_analysis_escape_latency_day5 <- metagen(
  smd, 
  se_smd, 
  data = day5_data,
  studlab = paste(paper_id, treatment_group, as.character(`age(month)`), acupoint_treatment, day, sep = "  |  "),
  sm = "SMD",
  method.tau = "DL",   
  comb.fixed = FALSE,  
  comb.random = TRUE
)
summary(meta_analysis_escape_latency_day5)
```

```{r}
forest(meta_analysis_escape_latency_day5,
       studlab = TRUE,
       textpos = 4,
       leftcols = c("studlab", "effect", "ci"),
       leftlabs = c("Paper id | Control Group | Age(month) | Acupoint | Day", "SMD", "95% CI"),
       colgap.left = "8mm",
       rightcols = c("w.random"),
       rightlabs = c("Weight"))
```

```{r}
funnel(meta_analysis_escape_latency_day5,
       xlab = "Standardised Mean Difference",
       ylab = "Standard Error",
       col = "blue",
       bg = "lightblue",
       pch = 21, # Use filled circles
       cex = 1.5) # Increase point size
```
```{r}
metabias(meta_analysis_escape_latency_day4, method.bias = "linreg")
```

```{r}
trimfill(meta_analysis_escape_latency_day4)
```


##### Escape latency Combined line plot with 95%CI
```{r}
meta_analysis_escape_latency_day1 <- metagen(
  smd, 
  se_smd, 
  data = day1_data,
  studlab = paste(paper_id, treatment_group, as.character(`age(month)`), acupoint_treatment, day, sep = "  |  "),
  sm = "SMD",
  method.tau = "DL",   
  comb.fixed = FALSE,  
  comb.random = TRUE
)

smd1 = meta_analysis_escape_latency_day1$TE.random
ci_lower1 = meta_analysis_escape_latency_day1$lower.random
ci_upper1 = meta_analysis_escape_latency_day1$upper.random

meta_analysis_escape_latency_day2 <- metagen(
  smd, 
  se_smd,
  data = day2_data,
  studlab = paste(paper_id, treatment_group, as.character(`age(month)`), acupoint_treatment, day, sep = "  |  "),
  sm = "SMD",
  method.tau = "DL",   
  comb.fixed = FALSE,  
  comb.random = TRUE
)

smd2 = meta_analysis_escape_latency_day2$TE.random
ci_lower2 = meta_analysis_escape_latency_day2$lower.random
ci_upper2 = meta_analysis_escape_latency_day2$upper.random

meta_analysis_escape_latency_day3 <- metagen(
  smd, 
  se_smd, 
  data = day3_data,
  studlab = paste(paper_id, treatment_group, as.character(`age(month)`), acupoint_treatment, day, sep = "  |  "),
  sm = "SMD",
  method.tau = "DL",   
  comb.fixed = FALSE,  
  comb.random = TRUE
)

smd3 = meta_analysis_escape_latency_day3$TE.random
ci_lower3 = meta_analysis_escape_latency_day3$lower.random
ci_upper3 = meta_analysis_escape_latency_day3$upper.random

meta_analysis_escape_latency_day4 <- metagen(
  smd, 
  se_smd,
  data = day4_data,
  studlab = paste(paper_id, treatment_group, as.character(`age(month)`), acupoint_treatment, day, sep = "  |  "),
  sm = "SMD",
  method.tau = "DL",   
  comb.fixed = FALSE,  
  comb.random = TRUE
)

smd4 = meta_analysis_escape_latency_day4$TE.random
ci_lower4 = meta_analysis_escape_latency_day4$lower.random
ci_upper4 = meta_analysis_escape_latency_day4$upper.random

meta_analysis_escape_latency_day5 <- metagen(
  smd, 
  se_smd,
  data = day5_data,
  studlab = paste(paper_id, treatment_group, as.character(`age(month)`), acupoint_treatment, day, sep = "  |  "),
  sm = "SMD",
  method.tau = "DL",   
  comb.fixed = FALSE,  
  comb.random = TRUE
)

smd5 = meta_analysis_escape_latency_day5$TE.random
ci_lower5 = meta_analysis_escape_latency_day5$lower.random
ci_upper5 = meta_analysis_escape_latency_day5$upper.random

days <- c(1,2,3,4,5)
smd <- c(smd1, smd2, smd3, smd4, smd5)
ci_upper <- c(ci_upper1, ci_upper2, ci_upper3, ci_upper4, ci_upper5)
ci_lower <- c(ci_lower1, ci_lower2, ci_lower3, ci_lower4, ci_lower5)

meta_analysis_escape_latency_combined = data.frame(days, smd, ci_upper, ci_lower)
```

```{r}
forest(meta_analysis_escape_latency_day5,
       studlab = TRUE,
       textpos = 4,
       leftcols = c("studlab", "effect", "ci"),
       leftlabs = c("Paper id | Control Group | Age(month) | Acupoint | Day", "SMD", "95% CI"),
       colgap.left = "8mm",
       rightcols = c("w.random"),
       rightlabs = c("Weight"))
```

```{r}
ggplot(meta_analysis_escape_latency_combined, aes(x = days, y = smd)) +
  geom_line(color = "blue") +
  geom_point(color = "red") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2, color = "black") +
  labs(title = "Escape Latency Meta-Analysis",
       x = "Day",
       y = "Standardized Mean Difference (SMD)",
       caption = "Error bars represent 95% confidence intervals") +
  theme_minimal()
```

#### Network Meta-Analysis
```{r}
day4_data
```

```{r}
day4_data <- day4_data %>%
  mutate(unique_id = paste(paper_id, treatment_group, acupoint_treatment, `age(month)`, sep = "_"))
day4_data
```


```{r}
netconnection(
  treat1 = day4_data$acupoint_treatment,
  treat2 = day4_data$treatment_group,
  studlab = day4_data$unique_id
)
```

```{r}
day4_data <- day4_data %>%
  mutate(treatment_group = "No Acupoint")

netmeta_analysis <- netmeta(
  TE = day4_data$smd,                          # Treatment effect (SMD)
  seTE = day4_data$se_smd,                     # Standard error of the treatment effect
  treat1 = day4_data$acupoint_treatment,       # The acupoints (treatment)
  treat2 = day4_data$treatment_group,          # The comparator (control groups)
  studlab = day4_data$unique_id,               # Study ID
  sm = "SMD",                                  # Standardized Mean Difference
  reference.group = "No Acupoint",
  details.chkmultiarm = TRUE
)
```

```{r}
summary(netmeta_analysis)
```


```{r}
# Plot the network graph
netgraph(netmeta_analysis)

# Create a forest plot for the network meta-analysis results
forest(netmeta_analysis)
```

```{r}
netsplit_result <- netsplit(netmeta_analysis)
pdf("Escape_latency_netsplit_forestplot.pdf", width = 9, height = 30) 
forest(netsplit_result, show = "all")
dev.off()
```


```{r}
# Prepare direct edges (those involving "No Acupoint")
edges_direct <- data.frame(
  from = gsub(":.*", "", netsplit_result$comparison[grep("No Acupoint", netsplit_result$comparison)]),
  to = gsub(".*:", "", netsplit_result$comparison[grep("No Acupoint", netsplit_result$comparison)]),
  weight = 1 / netsplit_result$direct.common[grep("No Acupoint", netsplit_result$comparison), "seTE"],
  type = "direct"
)

# Prepare indirect edges (those NOT involving "No Acupoint")
edges_indirect <- data.frame(
  from = gsub(":.*", "", netsplit_result$comparison[!grepl("No Acupoint", netsplit_result$comparison)]),
  to = gsub(".*:", "", netsplit_result$comparison[!grepl("No Acupoint", netsplit_result$comparison)]),
  weight = 1 / netsplit_result$indirect.common[!grepl("No Acupoint", netsplit_result$comparison), "seTE"],
  type = "indirect"
)

# Combine the direct and indirect edges into one dataframe
edges <- rbind(edges_direct, edges_indirect)

# Remove any NA values
edges <- edges[!is.na(edges$weight), ]

# Create graph object using edges
net_graph <- graph_from_data_frame(edges, directed = FALSE)

# Adjust edge colors and line types based on edge type
E(net_graph)$color <- ifelse(edges$type == "direct", "darkblue", "lightblue")
E(net_graph)$lty <- ifelse(edges$type == "direct", 1, 3)

# Add curvature to the edges for aesthetic purposes
E(net_graph)$curved <- rep(0.2, length(E(net_graph)))

plot(
  net_graph,
  vertex.label = V(net_graph)$name,
  vertex.label.dist = 2.5,
  vertex.label.font = 4,
  vertex.color = "lightblue",
  vertex.size = 12,
  vertex.label.cex = 0.8,
  vertex.label.color = "black",
  edge.width = E(net_graph)$weight,
  edge.color = E(net_graph)$color,
  edge.lty = E(net_graph)$lty,
  edge.curved = rep(0.1, length(E(net_graph))),
)

legend(
  "bottomright",  
  legend = c("Direct Relationship", "Indirect Relationship"),
  col = c("darkblue", "lightblue"),
  lty = c(1, 3),
  lwd = 3,
  cex = 0.8,
  bty = "n"
)
```
